apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kahook.fullname" . }}
  labels:
    {{- include "kahook.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      port: {{ .Values.config.server.port }}
      read_timeout: {{ .Values.config.server.readTimeout }}
      write_timeout: {{ .Values.config.server.writeTimeout }}
      idle_timeout: {{ .Values.config.server.idleTimeout }}
    auth:
      type: {{ .Values.auth.type }}
    kafka:
      acks: {{ .Values.config.kafka.acks }}
      retries: {{ .Values.config.kafka.retries }}
      compression_type: {{ .Values.config.kafka.compressionType }}
