apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kahook.fullname" . }}
  labels:
    {{- include "kahook.labels" . | nindent 4 }}
type: Opaque
stringData:
  KAFKA_BROKERS: {{ join "," .Values.kafka.brokers }}
  {{- if .Values.kafka.sasl.enabled }}
  KAFKA_SASL_USERNAME: {{ .Values.kafka.sasl.username }}
  KAFKA_SASL_PASSWORD: {{ .Values.kafka.sasl.password }}
  KAFKA_SASL_MECHANISM: {{ .Values.kafka.sasl.mechanism }}
  KAFKA_SECURITY_PROTOCOL: {{ .Values.kafka.securityProtocol }}
  {{- end }}
